In [1]:
import torch
from models import gp_model

# 假设 train_X 形状为 (N, 4) -> 4个工艺参数
train_X = torch.tensor([
    [100, 800, 0.1, 0.08],
    [120, 1000, 0.1, 0.10],
    [80,  900, 0.12, 0.07],
    [110, 1100, 0.1, 0.09],
    [95,  850, 0.11, 0.08],
    [105, 950, 0.1, 0.07],
    [90,  1000, 0.13, 0.1],
    [115, 970, 0.09, 0.08],
], dtype=torch.double)

# train_Y shape = (N, 3) -> 三个目标
train_Y = torch.tensor([
    [0.98, 8.5, 12.0],   # [Density, Roughness, Time]
    [0.96, 9.0, 10.5],
    [0.92, 10.5, 11.5],
    [0.97, 8.0, 10.0],
    [0.95, 9.3, 12.2],
    [0.96, 9.1, 11.0],
    [0.93, 10.0, 12.5],
    [0.97, 8.7, 10.3],
], dtype=torch.double)

model = gp_model.build_model(train_X, train_Y)
# TEST
test_X = torch.tensor([
    [100, 950, 0.1, 0.08],
    [110, 1000, 0.1, 0.09],
    [90, 900, 0.12, 0.07],
    [100, 800, 0.1, 0.08],
], dtype=torch.double)

mean_density, mean_roughness, mean_time = gp_model.predict(model, test_X)

print("Density prediction:\n", mean_density)
print("Roughness prediction:\n", mean_roughness)
print("Processing Time prediction:\n", mean_time)

Density prediction:
 tensor([[0.9594],
        [0.9601],
        [0.9217],
        [0.9798]], dtype=torch.float64)
Roughness prediction:
 tensor([[ 9.2566],
        [ 8.9068],
        [10.2445],
        [ 8.5048]], dtype=torch.float64)
Processing Time prediction:
 tensor([[11.5986],
        [10.3295],
        [12.1438],
        [11.9870]], dtype=torch.float64)
